@file:Suppress("CanConvertToMultiDollarString")

package com.jermey.quo.vadis.ksp.generators

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFile
import com.jermey.quo.vadis.ksp.QuoVadisClassNames
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * Generates the aggregated NavigationConfig that composes all discovered
 * module configs into a single config and registers it into NavigationConfigRegistry.
 *
 * Generated output example:
 * ```kotlin
 * @file:OptIn(InternalQuoVadisApi::class)
 *
 * @GeneratedConfig
 * object ComposeApp__AggregatedConfig : NavigationConfig by (
 *     ComposeAppNavigationConfig +
 *     Feature1NavigationConfig +
 *     Feature2NavigationConfig
 * ) {
 *     init {
 *         NavigationConfigRegistry.register(AppNavigation::class, this)
 *     }
 * }
 * ```
 */
class AggregatedConfigGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val packageName: String,
    private val modulePrefix: String
) {
    private val aggregatedObjectName = "${modulePrefix}__AggregatedConfig"

    /**
     * Generates the aggregated config object.
     *
     * @param rootClass The @NavigationRoot-annotated class
     * @param currentModuleConfigName The current module's generated config name (simple name)
     * @param dependencyConfigFqns Fully qualified names of discovered dependency configs, sorted
     * @param originatingFiles Source files for incremental processing
     */
    fun generate(
        rootClass: KSClassDeclaration,
        currentModuleConfigName: String,
        dependencyConfigFqns: List<String>,
        originatingFiles: List<KSFile>
    ) {
        logger.info("QuoVadis: Generating aggregated config $aggregatedObjectName")
        logger.info("QuoVadis:   Current module config: $currentModuleConfigName")
        logger.info("QuoVadis:   Dependency configs: ${dependencyConfigFqns.size}")

        // Build list of all config references (current module + dependencies)
        val allConfigNames = buildList {
            add("$packageName.$currentModuleConfigName")
            addAll(dependencyConfigFqns)
        }

        val fileSpec = FileSpec.builder(packageName, aggregatedObjectName)
            .addFileComment("Auto-generated by Quo Vadis KSP processor.\nDo not modify manually.")
            .addAnnotation(
                AnnotationSpec.builder(ClassName("kotlin", "OptIn"))
                    .addMember(
                        "%T::class",
                        ClassName("com.jermey.quo.vadis.core", "InternalQuoVadisApi")
                    )
                    .build()
            )
            .addType(buildAggregatedObject(rootClass, allConfigNames))
            .addFunction(buildInitFunction())
            .build()

        fileSpec.writeTo(codeGenerator, aggregating = true, originatingFiles)

        logger.info("QuoVadis: Successfully generated $aggregatedObjectName.kt")
    }

    private fun buildAggregatedObject(
        rootClass: KSClassDeclaration,
        allConfigFqns: List<String>
    ): TypeSpec {
        val rootClassName = rootClass.toClassName()

        // Build delegation expression: Config1 + Config2 + Config3
        val delegationExpr = buildDelegationExpression(allConfigFqns)

        val initBlock = CodeBlock.builder()
            .addStatement(
                "%T.register(%T::class, this)",
                QuoVadisClassNames.NAVIGATION_CONFIG_REGISTRY,
                rootClassName
            )
            .build()

        return TypeSpec.objectBuilder(aggregatedObjectName)
            .addAnnotation(QuoVadisClassNames.GENERATED_CONFIG)
            .addSuperinterface(QuoVadisClassNames.NAVIGATION_CONFIG, delegationExpr)
            .addInitializerBlock(initBlock)
            .build()
    }

    private fun buildDelegationExpression(allConfigFqns: List<String>): CodeBlock {
        if (allConfigFqns.size == 1) {
            return CodeBlock.of("%T", fqnToClassName(allConfigFqns[0]))
        }

        val builder = CodeBlock.builder()
        allConfigFqns.forEachIndexed { index, fqn ->
            if (index == 0) {
                builder.add("%T", fqnToClassName(fqn))
            } else {
                builder.add(" + %T", fqnToClassName(fqn))
            }
        }
        return builder.build()
    }

    /**
     * Generates a top-level `initQuoVadisNavigation()` function that forces
     * initialization of the aggregated config object, triggering its `init {}`
     * block which registers into [NavigationConfigRegistry].
     *
     * This is required for the KSP backend because Kotlin objects are lazily
     * initialized — the `init` block only runs when the object is first
     * referenced. The compiler plugin backend doesn't need this because it
     * rewrites `navigationConfig<T>()` call sites to reference the generated
     * object directly.
     */
    private fun buildInitFunction(): FunSpec {
        return FunSpec.builder("initQuoVadisNavigation")
            .addKdoc(
                "Initializes the Quo Vadis navigation configuration.\n\n" +
                    "Must be called once before `navigationConfig<T>()` when using the KSP backend.\n" +
                    "When using the compiler plugin backend, this call is a harmless no-op.\n" +
                    "Safe to call multiple times; idempotent via object initialization semantics."
            )
            .addStatement("%L", aggregatedObjectName)
            .build()
    }

    private fun fqnToClassName(fqn: String): ClassName {
        val lastDot = fqn.lastIndexOf('.')
        return if (lastDot > 0) {
            ClassName(fqn.substring(0, lastDot), fqn.substring(lastDot + 1))
        } else {
            ClassName("", fqn)
        }
    }
}
