package com.jermey.quo.vadis.core.navigation.config

/**
 * Marker interface for compiler-plugin-generated navigation configs.
 *
 * This interface extends [NavigationConfig] and is used exclusively by configs
 * generated by the Quo Vadis compiler plugin. It enables precise classpath
 * scanning during multi-module auto-discovery (Phase 4) without false
 * positives from user-defined manual configs.
 *
 * ## Auto-Discovery
 *
 * When `@NavigationRoot` is applied to a class in the application module,
 * the compiler plugin scans the classpath for all [GeneratedNavigationConfig]
 * implementors and aggregates them into a single composite config.
 *
 * ## Important
 *
 * - **Compiler-plugin-generated** configs implement this interface
 * - **KSP-generated** configs use [NavigationConfig] directly (backward compat)
 * - **User-defined** manual configs should use [NavigationConfig] directly
 *   and will NOT be included in auto-discovery
 */
interface GeneratedNavigationConfig : NavigationConfig
