package com.jermey.quo.vadis.core.navigation.config

/**
 * Marks a NavigationConfig implementation as generated by a Quo Vadis backend
 * (compiler plugin or KSP).
 *
 * Both backends annotate their generated config objects with this annotation.
 * Multi-module discovery scans for this annotation to find feature module configs
 * during aggregation.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.RUNTIME)
annotation class GeneratedConfig
