package com.jermey.quo.vadis.core.navigation.internal

import com.jermey.quo.vadis.core.InternalQuoVadisApi
import kotlinx.serialization.Serializable

/**
 * Metadata for a tab generated by KSP from @TabItem annotations.
 *
 * This is a minimal representation containing only the route identifier,
 * used for deep linking, serialization, and tab identification.
 *
 * ## Usage
 *
 * Tab UI customization (labels, icons) is done in `@TabsContainer` wrappers
 * using pattern matching on the `tabs: List<NavDestination>` property:
 * ```kotlin
 * scope.tabs.forEachIndexed { index, tab ->
 *     val (label, icon) = when (tab) {
 *         is HomeTab -> "Home" to Icons.Default.Home
 *         is ExploreTab -> "Explore" to Icons.Default.Explore
 *         else -> "Tab" to Icons.Default.Circle
 *     }
 *     // Use label and icon in your tab UI
 * }
 * ```
 *
 * @property route The route identifier for this tab's content
 */
@InternalQuoVadisApi
@Serializable
data class GeneratedTabMetadata(
    val route: String
)
