package com.jermey.quo.vadis.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.MAP
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * Generates code for @TabGraph annotated sealed classes.
 *
 * Generates:
 * - Tab configuration property
 * - Tab navigation container composable
 * - Tab graph builder function (optional)
 */
object TabGraphGenerator {

    fun generate(
        tabGraphInfo: TabGraphInfo,
        codeGenerator: CodeGenerator,
        logger: KSPLogger
    ) {
        val fileName = "${tabGraphInfo.className}Generated"

        val fileSpec = FileSpec.builder(tabGraphInfo.packageName, fileName)
            .addFileComment("Generated by Quo Vadis KSP. Do not edit manually.")
            .apply {
                // Add imports
                addImport("androidx.compose.runtime", "Composable")
                addImport("androidx.compose.ui", "Modifier")
                addImport("com.jermey.quo.vadis.core.navigation.core", "Navigator")
                addImport("com.jermey.quo.vadis.core.navigation.core", "TabNavigatorConfig")
                addImport("com.jermey.quo.vadis.core.navigation.compose", "rememberTabNavigator")
                addImport("com.jermey.quo.vadis.core.navigation.compose", "TabbedNavHost")
                addImport("com.jermey.quo.vadis.core.navigation.compose", "TabTransitionSpec")
                addImport("com.jermey.quo.vadis.core.navigation.core", "NavigationTransitions")

                // Generate config property
                generateTabConfig(tabGraphInfo)

                // Generate container composable
                generateTabContainer(tabGraphInfo)
            }
            .build()

        fileSpec.writeTo(
            codeGenerator,
            Dependencies(false, tabGraphInfo.classDeclaration.containingFile!!)
        )
        logger.info("Generated tab graph code: $fileName")
    }

    private fun FileSpec.Builder.generateTabConfig(tabGraphInfo: TabGraphInfo) {
        val initialTab = tabGraphInfo.getInitialTab()
        val primaryTab = tabGraphInfo.getPrimaryTab()

        val configInitializer = CodeBlock.builder()
            .addStatement("TabNavigatorConfig(")
            .indent()
            .add("allTabs = listOf(\n")
            .indent()
            .apply {
                tabGraphInfo.tabs.forEachIndexed { index, tab ->
                    val comma = if (index < tabGraphInfo.tabs.size - 1) "," else ""
                    addStatement("%L%L", tab.getSimpleReference(), comma)
                }
            }
            .unindent()
            .add("),\n")
            .addStatement("initialTab = %L,", initialTab.getSimpleReference())
            .addStatement("primaryTab = %L", primaryTab.getSimpleReference())
            .unindent()
            .addStatement(")")
            .build()

        addProperty(
            PropertySpec.builder(
                tabGraphInfo.getConfigName(),
                ClassName("com.jermey.quo.vadis.core.navigation.core", "TabNavigatorConfig")
            )
                .addKdoc(
                    """
                    Configuration for ${tabGraphInfo.className} tabs.
                    
                    Auto-generated from @TabGraph("${tabGraphInfo.name}") annotation.
                    
                    Tabs: ${tabGraphInfo.tabs.joinToString { it.name }}
                    Initial Tab: ${initialTab.name}
                    Primary Tab: ${primaryTab.name}
                    """.trimIndent()
                )
                .initializer(configInitializer)
                .build()
        )
    }

    @Suppress("LongMethod")
    private fun FileSpec.Builder.generateTabContainer(tabGraphInfo: TabGraphInfo) {
        val tabGraphsMapType = MAP.parameterizedBy(
            ClassName("com.jermey.quo.vadis.core.navigation.core", "TabDefinition"),
            ClassName("com.jermey.quo.vadis.core.navigation.core", "NavigationGraph")
        )

        addFunction(
            FunSpec.builder(tabGraphInfo.getContainerName())
                .addAnnotation(ClassName("androidx.compose.runtime", "Composable"))
                .addParameter("parentNavigator", ClassName("com.jermey.quo.vadis.core.navigation.core", "Navigator"))
                .addParameter(
                    ParameterSpec.builder("tabGraphs", tabGraphsMapType)
                        .build()
                )
                .addParameter(
                    ParameterSpec.builder(
                        "modifier",
                        ClassName("androidx.compose.ui", "Modifier")
                    )
                        .defaultValue("Modifier")
                        .build()
                )
                .addParameter(
                    ParameterSpec.builder(
                        "tabTransitionSpec",
                        ClassName("com.jermey.quo.vadis.core.navigation.compose", "TabTransitionSpec")
                    )
                        .defaultValue("TabTransitionSpec.Default")
                        .build()
                )
                .addParameter(
                    ParameterSpec.builder(
                        "defaultTransition",
                        ClassName("com.jermey.quo.vadis.core.navigation.core", "NavigationTransition")
                    )
                        .defaultValue("NavigationTransitions.Fade")
                        .build()
                )
                .addKdoc(
                    """
                    Tab navigation container for ${tabGraphInfo.className}.
                    
                    Auto-generated from @TabGraph("${tabGraphInfo.name}") annotation.
                    
                    @param parentNavigator The parent navigator for back press delegation
                    @param tabGraphs Map of tabs to their navigation graphs
                    @param modifier Modifier for the container
                    @param tabTransitionSpec Animation specification for tab transitions
                    @param defaultTransition Default transition for navigation within tabs
                    
                    Example usage:
                    ```kotlin
                    ${tabGraphInfo.getContainerName()}(
                        parentNavigator = navigator,
                        tabGraphs = mapOf(
                    ${tabGraphInfo.tabs.joinToString("\n") { tab ->
                    "        ${tab.getSimpleReference()} to ${tab.rootGraph.substringAfterLast(".")}.graph(),"
                }}
                        )
                    )
                    ```
                    """.trimIndent()
                )
                .addStatement(
                    "val tabState = rememberTabNavigator(%L, parentNavigator)",
                    tabGraphInfo.getConfigName()
                )
                .addStatement("")
                .addCode(
                    """
                    TabbedNavHost(
                        tabState = tabState,
                        tabGraphs = tabGraphs,
                        modifier = modifier,
                        tabTransitionSpec = tabTransitionSpec,
                        defaultTransition = defaultTransition,
                        navigator = parentNavigator
                    )
                    """.trimIndent()
                )
                .build()
        )
    }
}
