package com.jermey.quo.vadis.ksp.generators.base

/**
 * String templates for commonly generated code patterns.
 *
 * These templates provide consistent formatting across all generators
 * and centralize string literals for easier maintenance.
 *
 * ## Usage
 *
 * ```kotlin
 * // Use predefined templates
 * val header = StringTemplates.FILE_HEADER
 * val screensSection = StringTemplates.SCREENS_SECTION
 *
 * // Use builder functions
 * val deprecation = StringTemplates.deprecatedRegistryMessage("GeneratedScreenRegistry")
 *
 * // Access common parameter names
 * val navigatorParam = StringTemplates.Params.NAVIGATOR
 * ```
 */
object StringTemplates {

    // ═══════════════════════════════════════════════════════════════════════
    // FILE HEADERS
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * Standard file header comment for generated files.
     */
    const val FILE_HEADER = """
        |Auto-generated by Quo Vadis KSP processor.
        |Do not modify manually.
    """

    /**
     * KDoc for GeneratedNavigationConfig object.
     */
    val NAVIGATION_CONFIG_KDOC: String = """
        |Auto-generated navigation configuration.
        |
        |This object consolidates all navigation registries into a single,
        |composable configuration using the DSL-based approach.
        |
        |## Usage
        |
        |### One-liner
        |```kotlin
        |QuoVadisNavigation(MainTabs::class, GeneratedNavigationConfig)
        |```
        |
        |### Standard
        |```kotlin
        |val navigator = rememberQuoVadisNavigator(MainTabs::class, GeneratedNavigationConfig)
        |NavigationHost(navigator)  // Config is read from navigator
        |```
        |
        |### Multi-Module
        |```kotlin
        |val combinedConfig = GeneratedNavigationConfig + FeatureModuleConfig
        |val navigator = rememberQuoVadisNavigator(MainTabs::class, combinedConfig)
        |NavigationHost(navigator)
        |```
    """.trimMargin()

    /**
     * Short generated file header for compact files.
     */
    const val FILE_HEADER_SHORT = "Generated by Quo Vadis KSP - DO NOT EDIT"

    // ═══════════════════════════════════════════════════════════════════════
    // SECTION COMMENTS
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * Section separator line.
     */
    const val SECTION_SEPARATOR = "// ═══════════════════════════════════════════════"

    /**
     * Creates a section header comment.
     *
     * @param title The section title
     * @return Formatted section header string
     */
    fun sectionHeader(title: String): String = """
        |$SECTION_SEPARATOR
        |// $title
        |$SECTION_SEPARATOR
    """.trimMargin()

    /**
     * Section header for containers registration.
     */
    val CONTAINERS_SECTION: String = sectionHeader("CONTAINERS")

    /**
     * Section header for scopes registration.
     */
    val SCOPES_SECTION: String = sectionHeader("SCOPES")

    /**
     * Section header for transitions registration.
     */
    val TRANSITIONS_SECTION: String = sectionHeader("TRANSITIONS")

    /**
     * Section header for deep links registration.
     */
    val DEEP_LINKS_SECTION: String = sectionHeader("DEEP LINKS")

}
