package com.jermey.quo.vadis.ksp.generators.base

/**
 * String templates for commonly generated code patterns.
 *
 * These templates provide consistent formatting across all generators
 * and centralize string literals for easier maintenance.
 *
 * ## Usage
 *
 * ```kotlin
 * // Use predefined templates
 * val header = StringTemplates.FILE_HEADER
 * val screensSection = StringTemplates.SCREENS_SECTION
 *
 * // Use builder functions
 * val deprecation = StringTemplates.deprecatedRegistryMessage("GeneratedScreenRegistry")
 *
 * // Access common parameter names
 * val navigatorParam = StringTemplates.Params.NAVIGATOR
 * ```
 */
object StringTemplates {

    // ═══════════════════════════════════════════════════════════════════════
    // FILE HEADERS
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * Standard file header comment for generated files.
     */
    const val FILE_HEADER = """
        |Auto-generated by Quo Vadis KSP processor.
        |Do not modify manually.
    """

    /**
     * KDoc for GeneratedNavigationConfig object.
     */
    val NAVIGATION_CONFIG_KDOC: String = """
        |Auto-generated navigation configuration.
        |
        |This object consolidates all navigation registries into a single,
        |composable configuration using the DSL-based approach.
        |
        |## Usage
        |
        |### One-liner
        |```kotlin
        |QuoVadisNavigation(MainTabs::class)
        |```
        |
        |### Standard
        |```kotlin
        |val navigator = rememberQuoVadisNavigator(MainTabs::class)
        |NavigationHost(navigator, config = GeneratedNavigationConfig)
        |```
        |
        |### Advanced
        |```kotlin
        |NavigationHost(
        |    navigator = navigator,
        |    config = GeneratedNavigationConfig + FeatureModuleConfig
        |)
        |```
    """.trimMargin()

    /**
     * Short generated file header for compact files.
     */
    const val FILE_HEADER_SHORT = "Generated by Quo Vadis KSP - DO NOT EDIT"

    // ═══════════════════════════════════════════════════════════════════════
    // SECTION COMMENTS
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * Section separator line.
     */
    const val SECTION_SEPARATOR = "// ═══════════════════════════════════════════════"

    /**
     * Creates a section header comment.
     *
     * @param title The section title
     * @return Formatted section header string
     */
    fun sectionHeader(title: String): String = """
        |$SECTION_SEPARATOR
        |// $title
        |$SECTION_SEPARATOR
    """.trimMargin()

    /**
     * Section header for screens registration.
     */
    val SCREENS_SECTION: String = sectionHeader("SCREENS")

    /**
     * Section header for containers registration.
     */
    val CONTAINERS_SECTION: String = sectionHeader("CONTAINERS")

    /**
     * Section header for scopes registration.
     */
    val SCOPES_SECTION: String = sectionHeader("SCOPES")

    /**
     * Section header for transitions registration.
     */
    val TRANSITIONS_SECTION: String = sectionHeader("TRANSITIONS")

    /**
     * Section header for wrappers registration.
     */
    val WRAPPERS_SECTION: String = sectionHeader("WRAPPERS")

    /**
     * Section header for deep links registration.
     */
    val DEEP_LINKS_SECTION: String = sectionHeader("DEEP LINKS")

    /**
     * Section header for navigation roots.
     */
    val ROOTS_SECTION: String = sectionHeader("ROOTS")

    // ═══════════════════════════════════════════════════════════════════════
    // DEPRECATION MESSAGES
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * Deprecation message for old registry objects.
     *
     * @param registryName The name of the deprecated registry (e.g., "GeneratedScreenRegistry")
     * @return Formatted deprecation message with migration instructions
     */
    fun deprecatedRegistryMessage(registryName: String): String {
        val propertyName = registryName
            .removePrefix("Generated")
            .replaceFirstChar { it.lowercase() }
        return """
            |This registry is deprecated. Use GeneratedNavigationConfig instead.
            |
            |Migration:
            |```kotlin
            |// Before
            |val registry = $registryName
            |
            |// After
            |val registry = GeneratedNavigationConfig.$propertyName
            |```
        """.trimMargin()
    }

    /**
     * Deprecation message for old NavNode builder functions.
     *
     * @param functionName The deprecated function name
     * @param containerClass The container class name (without ::class)
     * @return Formatted deprecation message with migration instructions
     */
    fun deprecatedBuilderMessage(functionName: String, containerClass: String): String = """
        |This function is deprecated. Use GeneratedNavigationConfig.buildNavNode() instead.
        |
        |Migration:
        |```kotlin
        |// Before
        |val node = $functionName()
        |
        |// After
        |val node = GeneratedNavigationConfig.buildNavNode($containerClass::class)
        |```
    """.trimMargin()

    // ═══════════════════════════════════════════════════════════════════════
    // CODE SNIPPETS
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * Template for NavigationConfig implementation delegation.
     *
     * This template is used when creating a NavigationConfig implementation
     * that delegates to an inner config instance.
     */
    const val CONFIG_DELEGATION_TEMPLATE = """
        |override val screenRegistry = config.screenRegistry
        |override val wrapperRegistry = config.wrapperRegistry
        |override val scopeRegistry = config.scopeRegistry
        |override val transitionRegistry = config.transitionRegistry
        |override val containerRegistry = config.containerRegistry
        |override val deepLinkHandler = config.deepLinkHandler
        |
        |override fun buildNavNode(
        |    destinationClass: KClass<out Destination>,
        |    key: String?,
        |    parentKey: String?
        |): NavNode? = config.buildNavNode(destinationClass, key, parentKey)
        |
        |override fun plus(other: NavigationConfig): NavigationConfig =
        |    CompositeNavigationConfig(this, other)
    """

    /**
     * Generates a roots property template.
     *
     * @param rootClasses List of root class names (simple names, not qualified)
     * @return Kotlin property definition string
     */
    fun rootsPropertyTemplate(rootClasses: List<String>): String {
        if (rootClasses.isEmpty()) {
            return """
                |/**
                | * Root destinations available for navigation.
                | */
                |val roots: Set<KClass<out Destination>> = emptySet()
            """.trimMargin()
        }

        val classRefs = rootClasses.joinToString(",\n        ") { "$it::class" }
        return """
            |/**
            | * Root destinations available for navigation.
            | */
            |val roots: Set<KClass<out Destination>> = setOf(
            |    $classRefs
            |)
        """.trimMargin()
    }

    /**
     * Template for empty screen registry content function.
     */
    const val EMPTY_SCREEN_CONTENT = """
        |// No screens registered
        |Unit
    """

    /**
     * Template for empty scope registry.
     */
    const val EMPTY_SCOPE_REGISTRY = "// No scopes registered"

    // ═══════════════════════════════════════════════════════════════════════
    // PARAMETER PATTERNS
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * Common parameter names used in generated code.
     */
    object Params {
        /** Destination parameter name. */
        const val DESTINATION = "destination"

        /** Navigator parameter name. */
        const val NAVIGATOR = "navigator"

        /** Scope parameter name. */
        const val SCOPE = "scope"

        /** Key parameter name. */
        const val KEY = "key"

        /** Parent key parameter name. */
        const val PARENT_KEY = "parentKey"

        /** Scope key parameter name. */
        const val SCOPE_KEY = "scopeKey"

        /** Wrapper key parameter name. */
        const val WRAPPER_KEY = "wrapperKey"

        /** Initial tab parameter name. */
        const val INITIAL_TAB = "initialTab"

        /** Initial pane parameter name. */
        const val INITIAL_PANE = "initialPane"

        /** Shared transition scope parameter name. */
        const val SHARED_TRANSITION_SCOPE = "sharedTransitionScope"

        /** Animated visibility scope parameter name. */
        const val ANIMATED_VISIBILITY_SCOPE = "animatedVisibilityScope"

        /** Content lambda parameter name. */
        const val CONTENT = "content"
    }

    // ═══════════════════════════════════════════════════════════════════════
    // TYPE NAMES
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * Common type name strings for code generation.
     *
     * These are simple string representations, not ClassName instances.
     * Use when building string-based code or messages.
     */
    object Types {
        /** Destination type name. */
        const val DESTINATION = "Destination"

        /** Navigator type name. */
        const val NAVIGATOR = "Navigator"

        /** NavNode type name. */
        const val NAV_NODE = "NavNode"

        /** KClass type name. */
        const val K_CLASS = "KClass"

        /** NavTransition type name. */
        const val NAV_TRANSITION = "NavTransition"

        /** ScreenRegistry type name. */
        const val SCREEN_REGISTRY = "ScreenRegistry"

        /** WrapperRegistry type name. */
        const val WRAPPER_REGISTRY = "WrapperRegistry"

        /** ScopeRegistry type name. */
        const val SCOPE_REGISTRY = "ScopeRegistry"

        /** TransitionRegistry type name. */
        const val TRANSITION_REGISTRY = "TransitionRegistry"

        /** ContainerRegistry type name. */
        const val CONTAINER_REGISTRY = "ContainerRegistry"

        /** DeepLinkHandler type name. */
        const val DEEP_LINK_HANDLER = "DeepLinkHandler"

        /** NavigationConfig type name. */
        const val NAVIGATION_CONFIG = "NavigationConfig"

        /** CompositeNavigationConfig type name. */
        const val COMPOSITE_NAVIGATION_CONFIG = "CompositeNavigationConfig"

        /** ScreenNode type name. */
        const val SCREEN_NODE = "ScreenNode"

        /** StackNode type name. */
        const val STACK_NODE = "StackNode"

        /** TabNode type name. */
        const val TAB_NODE = "TabNode"

        /** PaneNode type name. */
        const val PANE_NODE = "PaneNode"
    }

    // ═══════════════════════════════════════════════════════════════════════
    // ERROR MESSAGES
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * Error message templates for KSP processing errors.
     *
     * These provide consistent, actionable error messages across all generators.
     */
    object Errors {
        /**
         * Error when no @Screen annotation is found for a destination.
         *
         * @param destClass The destination class name
         * @return Error message string
         */
        fun noScreenForDestination(destClass: String): String =
            "No @Screen annotation found for destination: $destClass"

        /**
         * Error when duplicate registration is detected.
         *
         * @param type The type of registration (e.g., "screen", "container")
         * @param key The duplicate key
         * @return Error message string
         */
        fun duplicateRegistration(type: String, key: String): String =
            "Duplicate $type registration for key: $key"

        /**
         * Error when an invalid container type is used.
         *
         * @param className The invalid class name
         * @return Error message string
         */
        fun invalidContainerType(className: String): String =
            "Invalid container type: $className. Must be @Tabs, @Stack, or @Pane"

        /**
         * Error when a required annotation is missing.
         *
         * @param annotation The missing annotation name (without @)
         * @param className The class missing the annotation
         * @return Error message string
         */
        fun missingRequiredAnnotation(annotation: String, className: String): String =
            "Missing required @$annotation annotation on: $className"

        /**
         * Error when a cyclic dependency is detected.
         *
         * @param path The dependency path showing the cycle
         * @return Error message string
         */
        fun cyclicDependency(path: List<String>): String =
            "Cyclic dependency detected: ${path.joinToString(" -> ")}"

        /**
         * Error when an invalid scope key is provided.
         *
         * @param scopeKey The invalid scope key
         * @return Error message string
         */
        fun invalidScopeKey(scopeKey: String): String =
            "Invalid scope key: $scopeKey. Scope keys must be non-empty strings."

        /**
         * Error when nested class resolution fails.
         *
         * @param className The class name that failed resolution
         * @return Error message string
         */
        fun nestedClassResolutionFailed(className: String): String =
            "Failed to resolve nested class: $className. Ensure the class is accessible."

        /**
         * Error when no root destination is found.
         *
         * @return Error message string
         */
        fun noRootDestination(): String =
            "No root destination found. At least one @Tabs, @Stack, or @Pane container must be defined."

        /**
         * Error when function signature doesn't match expected pattern.
         *
         * @param functionName The function name
         * @param expectedSignature Description of expected signature
         * @return Error message string
         */
        fun invalidFunctionSignature(functionName: String, expectedSignature: String): String =
            "Invalid function signature for '$functionName'. Expected: $expectedSignature"
    }
}
