package com.jermey.quo.vadis.core.navigation

import com.jermey.quo.vadis.core.InternalQuoVadisApi
import kotlinx.serialization.Serializable

/**
 * Metadata for a tab generated by KSP from @TabItem annotations.
 *
 * This is a simple string-based representation of tab metadata that is
 * generated at compile-time. For runtime UI rendering with icons,
 * use [com.jermey.quo.vadis.core.compose.scope.TabMetadata] which
 * supports ImageVector icons.
 *
 * ## Usage
 *
 * Generated functions like `getMainTabsMetadata()` return a list of this class:
 * ```kotlin
 * val tabs = getMainTabsMetadata()
 * tabs.forEach { tab ->
 *     // Use tab.label, tab.icon (string), tab.route
 * }
 * ```
 *
 * ## Converting to TabMetadata
 *
 * To convert to the runtime [TabMetadata] with ImageVector icons:
 * ```kotlin
 * val tabMetadata = generatedMetadata.map { generated ->
 *     TabMetadata(
 *         label = generated.label,
 *         icon = iconStringToVector(generated.icon), // Your icon mapping
 *         route = generated.route
 *     )
 * }
 * ```
 *
 * @property label Human-readable label for the tab (e.g., "Home")
 * @property icon Icon identifier string from @TabItem annotation (e.g., "home", "settings")
 * @property route The route identifier for this tab's content
 */
@InternalQuoVadisApi
@Serializable
data class GeneratedTabMetadata(
    val label: String,
    val icon: String,
    val route: String
)
